### ISSUE TITLE
Title Case functionality and hotkey

### ISSUE THREAD

**Issue by Riveascore** [jdc0589/CaseConversion#21]
Could you please add a hotkey for making things title case?

I'm thinking either of the following hotkeys would suit this, but would prefer the latter:

`ctrl + alt + c`, `ctrl + alt + t` (Title Case)
`ctrl + alt + c`, `ctrl + alt + j` (Jaden Smith Case)

**Comment by Riveascore** [comment]
I added the following to my `Packages/User`:

https://www.sublimetext.com/forum/viewtopic.php?f=5&t=8677

Then, added this to my user sublime-keymap:

```
  { "keys": ["ctrl+alt+c", "ctrl+alt+j"], 
    "command": "run_multiple_commands", 
    "args": {
      "commands": [
        { "command": "convert_to_pascal" },
        { "command": "convert_to_separate_words" }
      ]
    } 
  }  
```

Decided to go with **Jaden Smith Case** :P

**Comment by ismnoiet** [comment]
@Riveascore Title case ,upperCase and lowerCase are all built-in with sublime text so you don't have install any other plugin, just select your text and hit <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd> and select the wanted case

**Comment by jdc0589** [comment]
@ismnoiet bingo.  you can reopen this if that doesn't cover it somehow @Riveascore
