### ISSUE TITLE
Made a pypi package

### ISSUE THREAD

**Issue by AlejandroFrias** [jdc0589/CaseConversion#24]
Hey, wanted to thank you for your work on this plugin. I found myself needing a python package that did the same conversions and none seemed to exist that sufficed (or could handle `CONTANT_CASE` to `dash-case` conversion).

So I put it up on Pypi here: https://pypi.python.org/pypi/case_conversion/1.0.1
Here's the github repo: https://github.com/AlejandroFrias/case-conversion

I changed the names so it looked more like type casting, added some aliases for `dashcase` that are common and added some thorough testing for sanity check. Otherwise, it's a relatively straight forward port of the non-Sublime aspects of this plugin. You could even factor out that stuff now and import this...

I mostly wanted to let you know I did this in case you had any issues with how I gave you credit. If you want more or less credit, just let me know (but I did use your copy right and mentioned all the contributors in the README.

**Comment by jdc0589** [comment]
@AlejandroFrias sounds great to me! Thanks a bunch.
