### ISSUE TITLE
Does this plugin support ST3?

### ISSUE THREAD

**Issue by arvindch** [jdc0589/CaseConversion#33]
Hi,

The github and package-control description for this plugin say:
`Case conversion plugin (pascal, camel, snake) for sublime text 2`

Does this mean it does not support ST3?

Thanks.

**Comment by jdc0589** [comment]
nope, just means I haven't updated the readme in quite some time. Last I
checked it should be good to go in ST3.

**Comment by arvindch** [comment]
Cool, thanks!
