### ISSUE TITLE
Vim support?

### ISSUE THREAD

**Issue by blunket** [jdc0589/CaseConversion#34]
I love this plugin so much I can't remember what coding was like without it.

But I'm planning on an eventual conversion from SublimeText to Vim. Does this plugin possibly work in Vim? Or do you know of any alternatives that will?

It'd be really hard to give this plugin up.

**Comment by jdc0589** [comment]
@blunket unfortunately I do not know of any comparable vim plugins; but, I'm only a casual vim user.
CaseConversion is 100% tied to the sublime platform, but the algorithms being used are pretty basic, so I'm pretty sure it could be ported to VimL if someone wanted to.

If you find a good replacement, definitely let me know!
